# roluun.com + www.roluun.com
# Marketing / overview website (static HTML)
server {
    listen 80;
    server_name roluun.com www.roluun.com;

    location / {
        root /usr/share/nginx/marketing;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}
